name: Code quality check

on: [pull_request]

env:
  OUTPUT: Empty

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev
        sudo apt-get install -y cppcheck
        sudo apt-get install -y llvm-dev
        sudo apt-get install -y clang-tidy
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Create compile_commands.json
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .

    - name: cppcheck
      working-directory: ${{runner.workspace}}/build
      run: |
        cppcheck src --enable=all --suppress=missingInclude --inline-suppr --inconclusive --output-file=cppcheck.txt --project=compile_commands.json -i$GITHUB_WORKSPACE/dependencies


    - name: clang-tidy
      working-directory: ${{runner.workspace}}/build
      run: |
        run-clang-tidy $GITHUB_WORKSPACE/src > clang_tidy.txt 2>&1

    - shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        echo 'OUTPUT<<EOF' >> $GITHUB_ENV
        echo '<details> <summary> <h1> CPPCHECK </h1></summary>' >> $GITHUB_ENV
        cat cppcheck.txt >> $GITHUB_ENV
        echo '</details>' >> $GITHUB_ENV
        echo '<details> <summary> ## CLANG_TIDY </summary>' >> $GITHUB_ENV
        cat clang_tidy.txt >> $GITHUB_ENV
        echo '</details>' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'

    - name: Create comment
      if: ${{ steps.fc.outputs.comment-id == 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          This comment was written by a bot! $value

    - name: Update comment
      if: ${{ steps.fc.outputs.comment-id != 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          ${{ env.OUTPUT }}
        edit-mode: replace


